spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8004
mybatis:
  type-aliases-package: com.hzit.api.entity
  
spring:
  profiles: dev
  application:
    name: springcloud-dept  # 应用的名称   多实例 名称必须保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bj1901          # 数据库名称
    username: root
    password: root
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7004/eureka # eureka服务器的地址   单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance: 
    instance-id: springcloud-dept:8001  #设置访问的别名
    prefer-ip-address: true        #显示ip地址
info:                              #点击别名  访问info信息
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.hzit.api.entity
  
  
spring:
  profiles: test
  application:
    name: springcloud-dept  # 应用的名称   多实例 名称必须保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bj1901_2     # 数据库名称
    username: root
    password: root
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7005/eureka # eureka服务器的地址   单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance: 
    instance-id: springcloud-dept:8001  #设置访问的别名
    prefer-ip-address: true        #显示ip地址
info:                              #点击别名  访问info信息
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$